### ISSUE TITLE
max test accuracy: 0

### ISSUE THREAD

**Issue by mehransahandi** [martin-gorner/tensorflow-mnist-tutorial#12]
there is no error but my accuracy is always 0, How should I solve it ?

**Comment by jorgemadridportillo** [comment]
I have the same error here, using Linux Mint 17.3 and Python3.4.3. 

Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
max test accuracy: 0

**Comment by martin-gorner** [comment]
Is your loss NaN ?
Could it be one of the problems described on this page: https://codelabs.developers.google.com/codelabs/cloud-tensorflow-mnist/#7

If you are running one of the samples without any changes, then it is something else.

**Comment by jorgemadridportillo** [comment]
No, it is not even displaying the GUI, it seems like it is not even calling the training_step function for me...

**Comment by neoscreenager** [comment]
No GUI for me too. Program ends with max test accuracy: 0

**Comment by martin-gorner** [comment]
Have you tried upgrading to Python 3.5?
Have you tried updating your matplotlib library (pip3 install --upgrade matplotlib) ?

**Comment by jorgemadridportillo** [comment]
Updating to Python 3.5 solved the problem completely!, thanks.

**Comment by martin-gorner** [comment]
I'll leave this open for a while to hear from others.
Then I'll fold it into https://github.com/martin-gorner/tensorflow-mnist-tutorial/issues/5

**Comment by neoscreenager** [comment]
All is working well after upgrading to python3.5 and pulling the updated code. Thanks :)

Current environment where the updated code is working for me is python 3.5, matplotlib 2.0.0 and tensorflow 1.0.0.

**Comment by val620** [comment]
I have the same problem, and I'm running the program with CentOS 7.3.1611, Python 3.5.1,  matplotlib 2.0.0,  tensorflow 1.0.0.

**Comment by neoscreenager** [comment]
Is your code updated? If not then please update it to latest revision and then try.

**Comment by mehransahandi** [comment]
non of updates solved the problem, I just cancelled every GUI parts and then worked well, the only solution worked for me.

**Comment by neoscreenager** [comment]
@mehransahandi What is your environment?

**Comment by kakawait** [comment]
Did you try with other graphical engine like `TkAgg` or `Qt5Agg` (depends on `py-qt5`)?

**Comment by val620** [comment]
All code is updated, still doesn't work.
@mehransahandi  Can you elaborate?

**Comment by vladsandulescu** [comment]
Hi, I have the same issue. I get max accuracy 0 also. I am using a virtual environment, python 3.5.2, matplotlib 2.0.0 and I'm just cloning the repo and running the mnist_1.0softmax.py file.
I use Agg, but I would say the max accuracy 0 issue doesn't seem to be related to this. I don't even see the plots.

**Comment by KortVea** [comment]
I have had the same problem: no GUI for displaying graphs, after extracting mnist data, it goes directly to max accuracy = 0, and I've tried upgrading all to the latest( Python 2.7 in virtualenv, 3.6.1 in system with tensorflow...)
I solved it by checking (macOS) /Users/you/.matplotlib/matplotlibrc and make sure the configuration something like below
`backend : TkAgg`

**Comment by Lobsterrr** [comment]
I have the same problem. tensorflow-1.8.0; python 3.6.3 ; matplotlib-2.2.2. 
Still cannot work it out.
