### ISSUE TITLE
Error AttributeError: 'module' object has no attribute 'style'

### ISSUE THREAD

**Issue by minhnv-viosoft** [martin-gorner/tensorflow-mnist-tutorial#20]
I installed tensorflow ( python3 ) successfully 
and run test ( hello tensorflow ) OK.
but when I run 
```python
python3 mnist_1.0_softmax.py
```

got the error: 

Traceback (most recent call last):
  File "mnist_1.0_softmax.py", line 17, in <module>
    import tensorflowvisu
  File "/home/minh/git/tensorflow-mnist-tutorial/tensorflowvisu.py", line 19, in <module>
    plt.style.use(["ggplot", "tensorflowvisu.mplstyle"])
AttributeError: 'module' object has no attribute 'style'

**Comment by martin-gorner** [comment]
pip3 install --upgrade matplotlib
will probably solve this

**Comment by itsergiu** [comment]
Solution for "pip3 install --upgrade matplotlib" did not solve.
How to solve error?

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-49c421340cf6> in <module>()
----> 1 import tensorflowvisu
ModuleNotFoundError: No module named 'tensorflowvisu'
