### ISSUE TITLE
Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by sundisktop** [martin-gorner/tensorflow-mnist-tutorial#21]
Ubuntu 16.04
Python 3.5.2
Tensorflow 0.12.1 rc

Hello, I worked through Google Lab and on step 2 I got error:

sundisktop@sun:~/tensorflow-mnist-tutorial$ python3 mnist_1.0_softmax.py
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting data/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "mnist_1.0_softmax.py", line 78, in <module>
    I = tensorflowvisu.tf_format_mnist_images(X, Y, Y_)  # assembles 10x10 images by default
  File "/home/sundisktop/tensorflow-mnist-tutorial/tensorflowvisu.py", line 42, in tf_format_mnist_images
    everything_incorrect_first = tf.concat([incorrectly_recognised_indices, correctly_recognised_indices], 0) # images reordered with indeces of unrecognised images first
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by liufuyang** [comment]
Encountered the same, looks like some higher version tensorflow issue. (I was using Tensorflow 1.0)
http://stackoverflow.com/questions/41813665/tensorflow-slim-typeerror-expected-int32-got-list-containing-tensors-of-type
This might solve this specific issue but later I encountered a matplotlib type error...

**Comment by adithyakanchan** [comment]
you can convert your code from 0.12 to 1.0 using tf_upgrade.py

https://www.tensorflow.org/install/migration
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility

**Comment by martin-gorner** [comment]
the error on tf.concat is due to a difference in the order of parameters between TF 1.0 and earlier versions.
I have now updated the code to be TF 1.0 compliant. Git fetch and try again.

**Comment by sundisktop** [comment]
Seems like there was a problem with matplotlib. I changed code in module tensorflowvisu.py, in line 160:
      colors = [x['color'] for x in clist]
after that all works fine.
