### ISSUE TITLE
NotImplementedError: Surface.create_for_data: Not Implemented yet.

### ISSUE THREAD

**Issue by minhnv-viosoft** [martin-gorner/tensorflow-mnist-tutorial#22]
after installed successfully and run the first example

```ssh
python3 mnist_1.0_softmax.py
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.

**Comment by martin-gorner** [comment]
for these problems, the solution is usually to try and use different graphics backend in matplotlib:
import matplotlib
matplotlib.use('backend-name-here')

**Comment by martin-gorner** [comment]
closing without further updates
