### ISSUE TITLE
max test accuracy: 0

### ISSUE THREAD

**Issue by EllieElliegogo** [martin-gorner/tensorflow-mnist-tutorial#26]
it's strange that the first time i tried your code that was all right but today i tried again the max test accuracy is 0.
both time i didn't change anything in your code ,and i used python2.7 ,and there was no error reported.
looking for help anxiously,thanks!

**Comment by EllieElliegogo** [comment]
while i tried it on python3.5 and upgrade the matplotlib,it is all right now.

**Comment by martin-gorner** [comment]
great thanks
