### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead

### ISSUE THREAD

**Issue by rafalfirlejczyk** [martin-gorner/tensorflow-mnist-tutorial#27]
I am working with Windows 7/64, Phyton 3.6.0 Anaconda 4.3.0 (64bit), TF1.0.
I have just cloned the updated example from Github (fresh code from today morning).
I tried to  run the example **mnist_1.0_softmax.py** . The code has already the change +init = tf.global_variables_initializer()) from the commit.

It get the error, the same as a few people already mentioned :
**TypeError: Expected int32, got list containing Tensors of type '_Message' instead.**

The listing is shown here:

C:\Users\Public\Documents\Python Scripts\tensorflow-mnist-tutorial-master>python mnist_1.0_softmax.py
I d:\build\tensorflow\tensorflow_gpu-r0.12\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA librar
y cublas64_80.dll locally
I d:\build\tensorflow\tensorflow_gpu-r0.12\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA librar
y cudnn64_5.dll locally
I d:\build\tensorflow\tensorflow_gpu-r0.12\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA librar
y cufft64_80.dll locally
I d:\build\tensorflow\tensorflow_gpu-r0.12\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA librar
y nvcuda.dll locally
I d:\build\tensorflow\tensorflow_gpu-r0.12\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA librar
y curand64_80.dll locally
Extracting data\train-images-idx3-ubyte.gz
Extracting data\train-labels-idx1-ubyte.gz
Extracting data\t10k-images-idx3-ubyte.gz
Extracting data\t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "mnist_1.0_softmax.py", line 78, in <module>
    I = tensorflowvisu.tf_format_mnist_images(X, Y, Y_)  # assembles 10x10 images by default
  File "C:\Users\Public\Documents\Python Scripts\tensorflow-mnist-tutorial-master\tensorflowvisu.py", line 42, in tf_for
mat_mnist_images
    everything_incorrect_first = tf.concat([incorrectly_recognised_indices, correctly_recognised_indices], 0) # images r
eordered with indeces of unrecognised images first
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 176, in _constant_t
ensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 367, in make_tensor
_proto
    _AssertCompatible(values, dtype)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 302, in _AssertComp
atible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by martin-gorner** [comment]
You are running this against an old version of TF.
The order of arguments in tf.concat has changed between when TF went 1.0
That's the error you are getting: wrong arguments to tf.concat

**Comment by rafalfirlejczyk** [comment]
Thank you Martin. I am running your code against TF1.0 - newest version of TF. I thought you have converted the code already to be TF1.0 conform.

**Comment by rafalfirlejczyk** [comment]
I think I have two versions of TF on my PC - I will check it. Thank you

**Comment by rafalfirlejczyk** [comment]
In fact. I had the installation of Python 3.6 embedded in Anaconda 3 4.3.0 64 bits. The problem is that Python 3.6 does not support TF1.0 yet as mentioned here:
https://github.com/tensorflow/tensorflow/issues/6533
So I had to downgrade my Python from 3.6.0 to 3.5.2 using this command:
**conda install python=3.5.2**
as shown here:
http://chris35wills.github.io/conda_python_version/
After this change I was able to run the example mnist_1.0_softmax.py and got my first test accuracy of 91.88% and some nice graphs.
Thank you

**Comment by rafalfirlejczyk** [comment]
By the way running the last example mnist_4.2_batchnorm_convolutional.py produces the test accuracy between 99.47% and 99.52%  !

9900: ********* epoch 17 ********* test accuracy:0.9951 test loss: 1.71078
9920: accuracy:1.0 loss: 0.0121176 (lr:0.00014038566966228513)
9940: accuracy:1.0 loss: 0.00516154 (lr:0.000139883990816552)
9960: accuracy:1.0 loss: 0.00624482 (lr:0.00013938854392552862)
9980: accuracy:1.0 loss: 0.0275177 (lr:0.0001388992515746302)
10001: accuracy:1.0 loss: 0.00098337 (lr:0.00013839203478918145)
10001: ********* epoch 17 ********* test accuracy:0.9948 test loss: 1.7379

**Comment by martin-gorner** [comment]
oh yeah!
