### ISSUE TITLE
NO Data Training in Spyder

### ISSUE THREAD

**Issue by ZENGTLONG** [martin-gorner/tensorflow-mnist-tutorial#28]
I have installed the Anaconda and tensorflow 1.0. and then I started Spyder ,ran the file 'mnist_1.0_softmax.py',and a folder named 'data' appeared..Next ,I only saw a graph without any data.

**Comment by weichanh** [comment]
I encountered the same issiue. How was it resolved?

**Comment by martin-gorner** [comment]
I will guess this is an interaction between Spyder and matplotlib. If you get to the bottom of this please post and answer here but as for this project, this is out of scope.

**Comment by weichanh** [comment]
Yes, it is an interaction issue. The IPython console in Spyder does not work well. But it works perfectly if you open a Python console.
