### ISSUE TITLE
Multi-threads run

### ISSUE THREAD

**Issue by aevilorz** [martin-gorner/tensorflow-mnist-tutorial#29]
First of all, thanks for this helpful tutorial.
I tried to run minst_1.0_softmax.py on multi-threads in a CPU by changing the code to:
``` python
# placehoder and variable definations
# def training_step function
with tf.Session() as sess:
    with tf.device("/cpu:0"):
        sess.run(init)
        datavis.animate(...)

```
But it didn't work and the CPU utilization was still around 25%. 
Could you please tell me how to do?
Thanks!

**Comment by martin-gorner** [comment]
In the default state, iI see my CPU at 500%. I have an 4 cores/8 threads CPU. It looks about right.
When you specify /cpu:0, you restrict processing to one core

**Comment by aevilorz** [comment]
Well, i run the original minist_1.0_softmax.py again, and nothing changes.
But, when running rnn_train.py in Part 2, i see my CPU at almost 100%.
I received some messages in both cases, my OS is win10, is it relevant?
```
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
...
```

**Comment by martin-gorner** [comment]
closing without further updates
