### ISSUE TITLE
ImportError: No module named 'tensorflowvisu'

### ISSUE THREAD

**Issue by kuatroka** [martin-gorner/tensorflow-mnist-tutorial#30]
Hi, after a fresh install of the tensorflow-1.0.1 on Linux through virtual env and pip3 I'm getting error when trying to import tensorflowvisu.

`ImportError: No module named 'tensorflowvisu'`

import tensorflow works ok, but the tensorflowvisu does not.

**Comment by martin-gorner** [comment]
tensorflowvisu.py is a file sitting in this repository, root folder. Python normally looks for local files on import.

**Comment by kuatroka** [comment]
Thanks Martin, all is good now, I will close the issue. One side question. Is there a generic code or tutorial on how to create this type of visualisation (with Accuracy Scores and Cost Function metrics) for different/generic networks?
Thanks 

**Edit**
I uncommented the code that you indicated in the mnist_1.0_softmax.py and got all the metrics I need, Thanks
