### ISSUE TITLE
Slides download

### ISSUE THREAD

**Issue by smanaqvi83** [martin-gorner/tensorflow-mnist-tutorial#33]
Hi, I need to download the slides? How can I download them?

**Comment by martin-gorner** [comment]
The slides are here: [https://goo.gl/pHeXe7](https://goo.gl/pHeXe7)
When the short link resolves, remove "/pub...." at the end of the URL and you will be in the normal Google docs UI. You can get a PDF with speaker notes in the menu File > print settings and Preview
