### ISSUE TITLE
can't import tensorflow normally

### ISSUE THREAD

**Issue by EvanAbra** [martin-gorner/tensorflow-mnist-tutorial#34]
I've just used pip3 to upgrade tensorflow on my windows computer. The tensorflow has been download successfully, but something is wrong when I try importing tensorflow  in python. My python's version is 3.5 and is 64-bits, and my pip's version is 8.1.1.
The error report is as below.
![mrp f w nmc0ragt i0ju](https://cloud.githubusercontent.com/assets/27116366/24869498/0c98c638-1e46-11e7-9085-bd980921cff1.png)
![h9y9wnwso81 dv ch67 j](https://cloud.githubusercontent.com/assets/27116366/24869705/adab8e52-1e46-11e7-8b75-c68ae21e85bf.png)
I really can't figure out what happened. Can anyone help me? Thanks.

**Comment by martin-gorner** [comment]
I really don't know much about Python in windows, but people have been reporting success using Anaconda. See install instructions here: https://github.com/martin-gorner/tensorflow-mnist-tutorial/blob/master/INSTALL.txt

**Comment by martin-gorner** [comment]
Windows installation instructions have been updated in INSTALL.txt. I hope this solves your problem.
