### ISSUE TITLE
Anaconda can't run mnist_3.0_convolutional.py 

### ISSUE THREAD

**Issue by brucelau126** [martin-gorner/tensorflow-mnist-tutorial#37]
I run this file on my labtop: windows 10 + Anaconda  python3.5.2 

When run **mnist_3.0_convolutional.py** , the Anaconda will break down.
When I drag the file into the cmd window, it shows:
FileNotFoundError: [Errno 2] No such file or directory: 'tensorflowvisu.mplstyle'
OSError: 'tensorflowvisu.mplstyle' not found in the style library and input is not a valid URL or path. See `style.available` for list of available styles.

If you can tell me what's wrong wth it? And how can I deal with it?
Thank you very much!

**Comment by brucelau126** [comment]
To anyone who encounters this problem.
This is the original error report:
```
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:126] Couldn't open CUDA library cudnn64_5.dll
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:3517] Unable to load cuDNN DSO
```
After I downloaded the **Download cuDNN v5.1 (Jan 20, 2017), for CUDA 8.0**(ps: I installed **Download cuDNN v6.0 (March 23, 2017), for CUDA 8.0** first ) ,and copy the required **cudnn64_5.dll** into the relevant dir, the problem can be solved.

**Comment by martin-gorner** [comment]
Your first error seems to indicate an old version of matplotlib. I do not believe there is any connection to cuDNN. However, I am glad your problem is solved.
