### ISSUE TITLE
Install Tensorflow Anaconda / Windows

### ISSUE THREAD

**Issue by neoarena** [martin-gorner/tensorflow-mnist-tutorial#39]
Could you make a step by step guide/video on how to install Tensorflow and use it in a ide. There is always a new problem that pops out... Several of my friends have problems here and its super frustrating.

**Comment by martin-gorner** [comment]
I just merged a change to the installation instructions for Windows that should make this easier.
I know there can be issues but I do not think I can all the problems that i do not know about in a video. The basic installation when everything works correctly is just 2 steps, as describes in INSTALL.txt
