### ISSUE TITLE
Empty plots

### ISSUE THREAD

**Issue by micsodaki** [martin-gorner/tensorflow-mnist-tutorial#42]
First of all, thank you very much for this excellente tutorial.

Unfortunately I always get empty plots when I run the code. I've updated matplotlib, but nothing changed.
I use Python 3.5 and Spyder3.1.
Do you have any idea what can be the problem?

Thanks in advance!

**Comment by NatLun091238** [comment]
Most likely you have similar problem as I do (I use Python 3.5 and Spyder 3.1.4 on Windows 10). I get empty plots on top of this message "max test accuracy: 0". My problem is related to missing dependencies of matplotlib.

**Comment by micsodaki** [comment]
Could you solve it?

**Comment by NatLun091238** [comment]
Not yet. I think to check all dependencies one by one and then upgrade again matplotlib. I hope it'll do the job. How does it go for you?

**Comment by micsodaki** [comment]
I found a solution. I followed this post: http://stackoverflow.com/questions/23585126/how-do-i-get-interactive-plots-again-in-spyder-ipython-matplotlib.
I solved it by opening a new window for plot in spyder.

**Comment by NatLun091238** [comment]
Thank you a lot! It worked for me too.

**Comment by martin-gorner** [comment]
I'm glad you were able to solve this.
Please be aware that this tutorial uses visualisation which are updated in real time, which is not something iPython/Jupyter normally supports. In Spyder however, the article you point to seems to indicate that there is a way to make them work. Thank you for looking into it.
