### ISSUE TITLE
Guide for Installing TensorFlow and Python 3.5 on Windows

### ISSUE THREAD

**Issue by BSalita** [martin-gorner/tensorflow-mnist-tutorial#47]
Windows batch file for installing TensorFlow and Python 3.5 on Windows. The issue is that as of this date, TensorFlow is not updated to Python 3.6+ and will not install. Additionally, many systems have an incompatible version of Python. See REM comments for assumptions.

    REM download Anaconda3-4.2.0-Windows-x86_64.exe (contains python 3.5) from https://repo.continuum.io/archive/index.html
    REM Assumes download is in %USERPROFILE%\Downloads
    %USERPROFILE%\Downloads\Anaconda3-4.2.0-Windows-x86_64.exe

    REM change path to use Anaconda3 (python 3.5)
    PATH %USERPROFILE%\Anaconda3;%USERPROFILE%\Anaconda3\Scripts;%USERPROFILE%\Anaconda3\Library\bin;%PATH%

    REM update pip to 9.0 or later (mandatory)
    python -m pip install --upgrade pip

    REM tell conda where to load tensorflow
    conda config --add channels conda-forge

    REM elevate command (mandatory) and install tensorflow - use explicit path to conda "%USERPROFILE%\Anaconda3\scripts\conda install tensorflow"
    powershell.exe -Command start-process -verb runas cmd {/K "%USERPROFILE%\Anaconda3\scripts\conda install tensorflow"}
`

**Comment by martin-gorner** [comment]
I use tensorflow with Python 3.6 on mac so this is a bit surprising. I have not tested on Windows though.

**Comment by martin-gorner** [comment]
closing without further updates.
The recommended way of installing Tensorflow on Windows is to get Anaconda and pip install tensorflow in the Anaconda shell
