### ISSUE TITLE
Error in mnist_1.0_softmax.py file

### ISSUE THREAD

**Issue by EngFawadKhan** [martin-gorner/tensorflow-mnist-tutorial#49]
![image](https://user-images.githubusercontent.com/29304460/26993846-520ede16-4d7e-11e7-8ea8-0acc7fd88b8e.png)

I am getting this error, Here is a list of my pip libraries

I have installed tensorflow ver 1.2.0rc2
numpy 1.13.0 with all the dependencies

I tried to run it from Anaconda Shell it gave me the same error. I am new to this sorry.

**Comment by EngFawadKhan** [comment]
The Error is caused by one of the first lines of code in _mnist_1.0_softmax.py_ file:
```
from tensorflow.examples.tutorials.mnist import input_data as mnist_data
```

I tried to run this line in python shell and it worked but when I try to run _mnist_1.0_softmax.py_ file it gives me the mentioned error. I repeated the process multiple times but no results.

![image](https://user-images.githubusercontent.com/29304460/26996759-e524d516-4d8d-11e7-8872-e572ce478928.png)

As you can see here I tried to run this specific line of code which caused the error 2 times and it's pretty weird because it always runs on the 2nd time. When I try to run the mnist file twice with this line in it, it always gave me error.

**Comment by EngFawadKhan** [comment]
```
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]
 on win32
```
I am using these versions of python and anaconda

**Comment by EngFawadKhan** [comment]
This issue was solve by **LeonLiber** 

I will elaborate on my problem to help anyone else:

If you are receiving this kind of error:

copy and paste the below line of code in your **CMD**:

`pip install pandas==0.20. --force-reinstall`

I also had to upgrade my numpy to 1.13.0 using

`pip install --upgrade numpy`

I am not sure about this line of code so plz search it in google to get the right syntex.

**Comment by martin-gorner** [comment]
this looks like a TF 1.2rc2 and pandas incompatibility. This should get solved with the final release.
