### ISSUE TITLE
Python 3.4 compatibility

### ISSUE THREAD

**Issue by martin-gorner** [martin-gorner/tensorflow-mnist-tutorial#5]
Most Ubuntu installations still come with Python 3.4 and Matplotlib 1.3
The visualisation code has a problem in these conditions as reported here [b010098](https://github.com/martin-gorner/tensorflow-mnist-tutorial/commit/b010098ff0e4cddbc448fa4b24a5fec13e57ce31)

**Comment by salamatburj** [comment]
I am running code(mnist_1.0_softmax.py) but have this output. Only frames of the figure appear but no curves.
D:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Tensorflow version 1.5.1
Extracting data\train-images-idx3-ubyte.gz
Extracting data\train-labels-idx1-ubyte.gz
Extracting data\t10k-images-idx3-ubyte.gz
Extracting data\t10k-labels-idx1-ubyte.gz

max test accuracy: 0
All libraries are updated to latest version.

**Comment by martin-gorner** [comment]
this bug is obsolete
