### ISSUE TITLE
error while compiling the model

### ISSUE THREAD

**Issue by VishargShah** [martin-gorner/tensorflow-mnist-tutorial#55]
InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_3' with dtype float
	 [[Node: Placeholder_3 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by martin-gorner** [comment]
Not enough data to debug, sorry. Feel free to reopen an issue and make sure to describe what script you are trying to run when you get the error.
