### ISSUE TITLE
How to visualize?

### ISSUE THREAD

**Issue by SMZCC** [martin-gorner/tensorflow-mnist-tutorial#58]
- Thanks Martin for your efforts very much .
- I'm so curious about  how to create this type of visualization (with Accuracy Scores and Cost Function metrics) for different/generic networks? I think that is so cool! 
- If there is a tutorial ,I will be much honored. 
Thanks

**Comment by martin-gorner** [comment]
It's just standard Matplotlib code. I wrote this in Matplotlib to get animated visualisations but if you just want to follow your training and do not care about animations, please use Tensorboard.
