### ISSUE TITLE
Question related to compatible_convolutional_noise_shape function.

### ISSUE THREAD

**Issue by ninfueng** [martin-gorner/tensorflow-mnist-tutorial#64]
Hello, I have the question related to the compatible_convolutional_noise_shape function which is used in the dropout in the convolution layer. The problem is if I create weights as below and use it as input of the function
```
W1 = tf.Variable(tf.truncated_normal([3, 3, 3, 64], mean = 0.0, stddev = 0.1), name = 'W1')
```
The output will be  [3 1 1 64] which is not the same shape as W1 that is [3 3 3 64]. The question is why we create the noise shape that is not equal to the shape of input of the function?

**Comment by martin-gorner** [comment]
Hi, the noise shape for dropout has a specific syntax. In the noise_shape parameter, 1 means "keep the dropout mask the same when this dimension changes". A value equal to the dimension at that position in the shape means "draw a new dropout mask every time this dimension changes.

In convolutional layers, your inputs typically have this shape: [batch, x, y, filter]. You could use that as your noise shape but in convolutional layers, you get better results (really, I tried and you can try too) when dropout is used consistently with the way "neurons" work in convolutional layers. When convolving the image with a filter, the same filter weights are used at every position in the image where the filter is applied. So it kind of makes sense that the same dropout mask would be used at every position too. Of course, when you move to the next image in the batch or the next filter, you draw a new dropout mask. This is called "spatial dropout" and the appropriate mask parameter for this is [batch, 1, 1, filter]

See the documentation here: https://www.tensorflow.org/api_docs/python/tf/layers/dropout
