### ISSUE TITLE
Tensorflow 0.11 is required (not just compatible)

### ISSUE THREAD

**Issue by simon-clematide** [martin-gorner/tensorflow-mnist-tutorial#7]
The optional argument `validation_size` is not supported by Tensorflow 0.10.
`mnist = read_data_sets("data", one_hot=True, reshape=False, validation_size=0)`

Just in case someone wants to try this on older version.

**Comment by martin-gorner** [comment]
Thank you for mentioning this.
Until Tensorflow hits 1.0, I will be keeping up with the latest version only.
