### ISSUE TITLE
Jupyter notebook

### ISSUE THREAD

**Issue by msteinmn** [martin-gorner/tensorflow-mnist-tutorial#9]
Great tutorial. Would love to use this in a class. Could not figure out how to run this within a Jupyter notebook so that the visualization works. Alternatively, would you have some instructions on how to run this in a Docker container on Mac/Windows so that the Display attaches properly?

**Comment by martin-gorner** [comment]
The visualisation is animated in real time as new data comes in. Jupiter notebooks have no animation support by design. So this is not possible.

You will have to remove the visualisations to make this work in a Jupiter notebook which is not hard.
